//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppPFINAL.BD.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarjeta
    {
      
        public long NumeroTarjeta { get; set; }

      
        public string TipoTarjeta { get; set; }

     
        public int LimiteCredito { get; set; }
     
        public int MontoExtra { get; set; }

       
        public System.DateTime FechaActivacion { get; set; }
        public string Origen { get; set; }
        public bool EstadoTarjeta { get; set; }

       
        public string TipoInteres { get; set; }
        
    
        public int Cedula { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
